---
title: 'Minecraft: Bedrock Edition Documenation'
timezone: UTC
collections:
  docs:
    title: Docs
    output: true
    permalink: "/"
  posts:
    title: Posts
    output: true
  static:
    title: Static
    output: false
    permalink: "/static"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: docs
  values:
    layout: page
encoding: UTF-8
